apiVersion: apps/v1
kind: Deployment
metadata:
  name: frame-combination-deployment-2
  labels: 
    app: frame-combination-deployment-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frame-combination-deployment-2
  template:
    metadata:
      labels:
        app: frame-combination-deployment-2
    spec:
      containers:
      - name: frame-combination-deployment-2
        image: kume4352/frame_combination:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8002
---

apiVersion: v1
kind: Service
metadata:
  name: frame-combination-deployment-service-2
spec:
  selector:
    app: frame-combination-deployment-2
  ports:
  - port: 8002
    targetPort: 8002
  type: ClusterIP