apiVersion: apps/v1
kind: Deployment
metadata:
  name: obj-detection-deployment-5
  labels: 
    app: obj-detection-deployment-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obj-detection-deployment-5
  template:
    metadata:
      labels:
        app: obj-detection-deployment-5
    spec:
      containers:
      - name: obj-detection-deployment-5
        image: kume4352/obj_detection:latest
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8001
---

apiVersion: v1
kind: Service
metadata:
  name: obj-detection-deployment-5-service
  labels:
    run: obj-detection-deployment-5
spec:
  selector:
    app: obj-detection-deployment-5
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP